[build]
  command = "npm i -g pnpm && pnpm i -store-dir=node_modules/.pnpm-store && pnpm run website -- build"
  publish = "website/public"

[build.environment]
    # This essentially means "don't run pnpm install"
    NPM_FLAGS="--prefix=/"
